### ISSUE TITLE
Script should create a output directory in working dir

### ISSUE THREAD

**Issue by syentix** [syentix/japanese-md-parser#2]
Currently the script creates files that just have an extended name to show that they have been parsed.
Put in some code, that will create an output directory and save all parsed files in there instead of stacking them onto each other in the current directory.

This should be possible without new libraries.

**Comment by mecm1993** [comment]
Hi @syentix I would like to work on this feature

**Comment by syentix** [comment]
You probably already know the drill, right? Let me know if you need help though!

**Comment by syentix** [comment]
Thank you for working on my repo, have fun and good luck with the hacktoberfest :)
